services:
  - type: web
    name: soundproofing-calculator
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo "Solutions directory contents:"
      ls -la solutions/
      echo "Python path:"
      python -c "import sys; print('\n'.join(sys.path))"
    startCommand: |
      PYTHONPATH=$PYTHONPATH:$(pwd) gunicorn app:app
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: "10000"
    healthCheckPath: /health