   # Update render.yaml to use Render's PORT
   services:
     - type: web
       name: soundproofing-calculator
       env: python
       buildCommand: pip install -r requirements.txt
       startCommand: gunicorn app:app
       envVars:
         - key: MONGODB_URI
           sync: false
         # Remove the PORT variable - Render will set this automatically
       healthCheckPath: /
       autoDeploy: true